steps:
  # Build and Deploy to Cloud Run
  - name: google/cloud-sdk
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "api",
        "--source",
        ".",
        "--set-env-vars",
        "VERSION=${TAG_NAME}",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
